name: Draw keymap
on:
  push:
    paths:
      - 'config/*.keymap'
      - 'config/boards/shields/totem/*.dtsi'
      - '.github/workflows/draw.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@v0.23.0
    permissions:
      contents: write
    with:
      keymap_patterns: 'config/*.keymap'
      commit_message: 'keymap-drawer render'
